### ISSUE TITLE
Youtube Speed Changer Bug

### ISSUE THREAD

**Issue by GrantHuff** [adriancarriger/youtube-speed-changer#48]
While writing a comment for a youtube video, the speed changer will still be in effect and change the speed and start point of said video.

Otherwise, great work!

**Comment by adriancarriger** [comment]
Hi @GrantHuff,  thanks for reporting this issue! 👍 I just fixed this and it should go live automatically within about an hour when version 1.5.80 hits the Chrome web store. Hope you and your family are doing well, and have a great fourth! 🎆 🎆 🎆

**Comment by GrantHuff** [comment]
Thanks! Hope that you're 4th of July is good as well. 

    On Saturday, July 1, 2017 4:24 PM, Adrian Carriger <notifications@github.com> wrote:
 

 Hi @GrantHuff, thanks for reporting this issue! 👍 I just fixed this and it should go live automatically within about an hour when version 1.5.80 hits the Chrome web store. Hope you and your family are doing well, and have a great fourth! 🎆 🎆 🎆 —
